services:
  digit-cardapp: 
    container_name: digit-cardappcontainer
    build: .
    image: digit-cardapp:v1
    ports: 
    - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks : 
   internalnet : 
      driver : bridge